# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.srcs/sources_1/new/LFSR4_5.vhd}
  {C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.srcs/sources_1/new/sev_seg.vhd}
  {C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.srcs/sources_1/new/mpg.vhd}
  {C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.srcs/sources_1/new/main_fpga.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.srcs/constrs_1/new/basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Andrei Eminovici/Desktop/AN2SEM1/Linear_Feedback_Shift_Register/LinearFeedbackShiftRegister/LinearFeedbackShiftRegister.srcs/constrs_1/new/basys3.xdc}}]


synth_design -top main_fpga -part xc7a35tcpg236-1


write_checkpoint -force -noxdef main_fpga.dcp

catch { report_utilization -file main_fpga_utilization_synth.rpt -pb main_fpga_utilization_synth.pb }
